"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpotTest__factory = exports.SpotIntegrationTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var SpotIntegrationTest__factory_1 = require("./SpotIntegrationTest__factory");
Object.defineProperty(exports, "SpotIntegrationTest__factory", { enumerable: true, get: function () { return SpotIntegrationTest__factory_1.SpotIntegrationTest__factory; } });
var SpotTest__factory_1 = require("./SpotTest__factory");
Object.defineProperty(exports, "SpotTest__factory", { enumerable: true, get: function () { return SpotTest__factory_1.SpotTest__factory; } });
