/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SpotIntegrationTest__factory } from "./SpotIntegrationTest__factory";
export { SpotTest__factory } from "./SpotTest__factory";
