/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFeeController,
  IFeeControllerInterface,
} from "../../FeeController.sol/IFeeController";

const _abi = [
  {
    type: "function",
    name: "getSpotFee",
    inputs: [
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
      {
        name: "tokenIn",
        type: "address",
        internalType: "address",
      },
      {
        name: "tokenOut",
        type: "address",
        internalType: "address",
      },
      {
        name: "amountIn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "adapter",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "feeAmount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "feeRecipient",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IFeeController__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeControllerInterface {
    return new Interface(_abi) as IFeeControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFeeController {
    return new Contract(address, _abi, runner) as unknown as IFeeController;
  }
}
