"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFeeController__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "getSpotFee",
        inputs: [
            {
                name: "user",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenIn",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenOut",
                type: "address",
                internalType: "address",
            },
            {
                name: "amountIn",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "adapter",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "feeAmount",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "feeRecipient",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
];
class IFeeController__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IFeeController__factory = IFeeController__factory;
IFeeController__factory.abi = _abi;
