/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FeeController__factory } from "./FeeController__factory";
export { IFeeController__factory } from "./IFeeController__factory";
