"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFeeController__factory = exports.FeeController__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FeeController__factory_1 = require("./FeeController__factory");
Object.defineProperty(exports, "FeeController__factory", { enumerable: true, get: function () { return FeeController__factory_1.FeeController__factory; } });
var IFeeController__factory_1 = require("./IFeeController__factory");
Object.defineProperty(exports, "IFeeController__factory", { enumerable: true, get: function () { return IFeeController__factory_1.IFeeController__factory; } });
