"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EdgeCaseTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EdgeCaseTest__factory_1 = require("./EdgeCaseTest__factory");
Object.defineProperty(exports, "EdgeCaseTest__factory", { enumerable: true, get: function () { return EdgeCaseTest__factory_1.EdgeCaseTest__factory; } });
