"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AerodromeAdapterTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AerodromeAdapterTest__factory_1 = require("./AerodromeAdapterTest__factory");
Object.defineProperty(exports, "AerodromeAdapterTest__factory", { enumerable: true, get: function () { return AerodromeAdapterTest__factory_1.AerodromeAdapterTest__factory; } });
