/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FeeControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adapterFeeBps"
      | "baseFeeBps"
      | "getSpotFee"
      | "maxFeeBps"
      | "owner"
      | "pairFeeBps"
      | "renounceOwnership"
      | "setAdapterFeeBps"
      | "setBaseFeeBps"
      | "setMaxFeeBps"
      | "setPairFeeBps"
      | "setTreasury"
      | "setUserDiscountBps"
      | "transferOwnership"
      | "treasury"
      | "userDiscountBps"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterFeeBpsSet"
      | "BaseFeeBpsSet"
      | "MaxFeeBpsSet"
      | "OwnershipTransferred"
      | "PairFeeBpsSet"
      | "TreasurySet"
      | "UserDiscountBpsSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adapterFeeBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "baseFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpotFee",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "maxFeeBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pairFeeBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdapterFeeBps",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPairFeeBps",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserDiscountBps",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDiscountBps",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "adapterFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSpotFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdapterFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPairFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserDiscountBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDiscountBps",
    data: BytesLike
  ): Result;
}

export namespace AdapterFeeBpsSetEvent {
  export type InputTuple = [adapter: AddressLike, newFeeBps: BigNumberish];
  export type OutputTuple = [adapter: string, newFeeBps: bigint];
  export interface OutputObject {
    adapter: string;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseFeeBpsSetEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxFeeBpsSetEvent {
  export type InputTuple = [newMaxFeeBps: BigNumberish];
  export type OutputTuple = [newMaxFeeBps: bigint];
  export interface OutputObject {
    newMaxFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairFeeBpsSetEvent {
  export type InputTuple = [pairKey: BytesLike, newFeeBps: BigNumberish];
  export type OutputTuple = [pairKey: string, newFeeBps: bigint];
  export interface OutputObject {
    pairKey: string;
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDiscountBpsSetEvent {
  export type InputTuple = [user: AddressLike, newDiscountBps: BigNumberish];
  export type OutputTuple = [user: string, newDiscountBps: bigint];
  export interface OutputObject {
    user: string;
    newDiscountBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeController extends BaseContract {
  connect(runner?: ContractRunner | null): FeeController;
  waitForDeployment(): Promise<this>;

  interface: FeeControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adapterFeeBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  baseFeeBps: TypedContractMethod<[], [bigint], "view">;

  getSpotFee: TypedContractMethod<
    [
      user: AddressLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      adapter: AddressLike
    ],
    [[bigint, string] & { feeAmount: bigint; feeRecipient: string }],
    "view"
  >;

  maxFeeBps: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pairFeeBps: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAdapterFeeBps: TypedContractMethod<
    [_adapter: AddressLike, _newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBaseFeeBps: TypedContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxFeeBps: TypedContractMethod<
    [_newMaxFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPairFeeBps: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, _newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setUserDiscountBps: TypedContractMethod<
    [_user: AddressLike, _newDiscountBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  userDiscountBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adapterFeeBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSpotFee"
  ): TypedContractMethod<
    [
      user: AddressLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      adapter: AddressLike
    ],
    [[bigint, string] & { feeAmount: bigint; feeRecipient: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pairFeeBps"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAdapterFeeBps"
  ): TypedContractMethod<
    [_adapter: AddressLike, _newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBaseFeeBps"
  ): TypedContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxFeeBps"
  ): TypedContractMethod<[_newMaxFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPairFeeBps"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, _newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserDiscountBps"
  ): TypedContractMethod<
    [_user: AddressLike, _newDiscountBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userDiscountBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AdapterFeeBpsSet"
  ): TypedContractEvent<
    AdapterFeeBpsSetEvent.InputTuple,
    AdapterFeeBpsSetEvent.OutputTuple,
    AdapterFeeBpsSetEvent.OutputObject
  >;
  getEvent(
    key: "BaseFeeBpsSet"
  ): TypedContractEvent<
    BaseFeeBpsSetEvent.InputTuple,
    BaseFeeBpsSetEvent.OutputTuple,
    BaseFeeBpsSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxFeeBpsSet"
  ): TypedContractEvent<
    MaxFeeBpsSetEvent.InputTuple,
    MaxFeeBpsSetEvent.OutputTuple,
    MaxFeeBpsSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PairFeeBpsSet"
  ): TypedContractEvent<
    PairFeeBpsSetEvent.InputTuple,
    PairFeeBpsSetEvent.OutputTuple,
    PairFeeBpsSetEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;
  getEvent(
    key: "UserDiscountBpsSet"
  ): TypedContractEvent<
    UserDiscountBpsSetEvent.InputTuple,
    UserDiscountBpsSetEvent.OutputTuple,
    UserDiscountBpsSetEvent.OutputObject
  >;

  filters: {
    "AdapterFeeBpsSet(address,uint256)": TypedContractEvent<
      AdapterFeeBpsSetEvent.InputTuple,
      AdapterFeeBpsSetEvent.OutputTuple,
      AdapterFeeBpsSetEvent.OutputObject
    >;
    AdapterFeeBpsSet: TypedContractEvent<
      AdapterFeeBpsSetEvent.InputTuple,
      AdapterFeeBpsSetEvent.OutputTuple,
      AdapterFeeBpsSetEvent.OutputObject
    >;

    "BaseFeeBpsSet(uint256)": TypedContractEvent<
      BaseFeeBpsSetEvent.InputTuple,
      BaseFeeBpsSetEvent.OutputTuple,
      BaseFeeBpsSetEvent.OutputObject
    >;
    BaseFeeBpsSet: TypedContractEvent<
      BaseFeeBpsSetEvent.InputTuple,
      BaseFeeBpsSetEvent.OutputTuple,
      BaseFeeBpsSetEvent.OutputObject
    >;

    "MaxFeeBpsSet(uint256)": TypedContractEvent<
      MaxFeeBpsSetEvent.InputTuple,
      MaxFeeBpsSetEvent.OutputTuple,
      MaxFeeBpsSetEvent.OutputObject
    >;
    MaxFeeBpsSet: TypedContractEvent<
      MaxFeeBpsSetEvent.InputTuple,
      MaxFeeBpsSetEvent.OutputTuple,
      MaxFeeBpsSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PairFeeBpsSet(bytes32,uint256)": TypedContractEvent<
      PairFeeBpsSetEvent.InputTuple,
      PairFeeBpsSetEvent.OutputTuple,
      PairFeeBpsSetEvent.OutputObject
    >;
    PairFeeBpsSet: TypedContractEvent<
      PairFeeBpsSetEvent.InputTuple,
      PairFeeBpsSetEvent.OutputTuple,
      PairFeeBpsSetEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;

    "UserDiscountBpsSet(address,uint256)": TypedContractEvent<
      UserDiscountBpsSetEvent.InputTuple,
      UserDiscountBpsSetEvent.OutputTuple,
      UserDiscountBpsSetEvent.OutputObject
    >;
    UserDiscountBpsSet: TypedContractEvent<
      UserDiscountBpsSetEvent.InputTuple,
      UserDiscountBpsSetEvent.OutputTuple,
      UserDiscountBpsSetEvent.OutputObject
    >;
  };
}
