/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FeeController } from "./FeeController";
export type { IFeeController } from "./IFeeController";
