"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProtocolFeeTest__factory = exports.MockAdapter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockAdapter__factory_1 = require("./MockAdapter__factory");
Object.defineProperty(exports, "MockAdapter__factory", { enumerable: true, get: function () { return MockAdapter__factory_1.MockAdapter__factory; } });
var ProtocolFeeTest__factory_1 = require("./ProtocolFeeTest__factory");
Object.defineProperty(exports, "ProtocolFeeTest__factory", { enumerable: true, get: function () { return ProtocolFeeTest__factory_1.ProtocolFeeTest__factory; } });
