"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AMMAggregatorTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AMMAggregatorTest__factory_1 = require("./AMMAggregatorTest__factory");
Object.defineProperty(exports, "AMMAggregatorTest__factory", { enumerable: true, get: function () { return AMMAggregatorTest__factory_1.AMMAggregatorTest__factory; } });
