"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CounterScript__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CounterScript__factory_1 = require("./CounterScript__factory");
Object.defineProperty(exports, "CounterScript__factory", { enumerable: true, get: function () { return CounterScript__factory_1.CounterScript__factory; } });
