/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Counter, CounterInterface } from "../Counter";

const _abi = [
  {
    type: "function",
    name: "increment",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "number",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setNumber",
    inputs: [
      {
        name: "newNumber",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

const _bytecode =
  "0x608060405234601c57600e6020565b6102c561002b82396102c590f35b6026565b60405190565b5f80fdfe60806040526004361015610013575b6101b0565b61001d5f3561004c565b80633fb5c1cb146100475780638381f58a146100425763d09de08a0361000e5761017d565b610148565b6100a9565b60e01c90565b60405190565b5f80fd5b5f80fd5b90565b61006c81610060565b0361007357565b5f80fd5b9050359061008482610063565b565b9060208282031261009f5761009c915f01610077565b90565b61005c565b5f0190565b346100d7576100c16100bc366004610086565b610211565b6100c9610052565b806100d3816100a4565b0390f35b610058565b5f9103126100e657565b61005c565b1c90565b90565b61010290600861010793026100eb565b6100ef565b90565b9061011591546100f2565b90565b6101235f5f9061010a565b90565b61012f90610060565b9052565b9190610146905f60208501940190610126565b565b34610178576101583660046100dc565b610174610163610118565b61016b610052565b91829182610133565b0390f35b610058565b346101ab5761018d3660046100dc565b610195610273565b61019d610052565b806101a7816100a4565b0390f35b610058565b5f80fd5b5f1b90565b906101c55f19916101b4565b9181191691161790565b90565b6101e66101e16101eb92610060565b6101cf565b610060565b90565b90565b9061020661020161020d926101d2565b6101ee565b82546101b9565b9055565b61021b905f6101f1565b565b5f1c90565b61022e6102339161021d565b6100ef565b90565b6102409054610222565b90565b634e487b7160e01b5f52601160045260245ffd5b61026090610060565b5f19811461026e5760010190565b610243565b61028d6102876102825f610236565b610257565b5f6101f1565b56fea2646970667358221220e60568cba118eaafcedb006fe923c3fdd44ef22022079583b179c52dbfcea9e864736f6c634300081e0033";

type CounterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CounterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Counter__factory extends ContractFactory {
  constructor(...args: CounterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Counter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Counter__factory {
    return super.connect(runner) as Counter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CounterInterface {
    return new Interface(_abi) as CounterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Counter {
    return new Contract(address, _abi, runner) as unknown as Counter;
  }
}
