"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFactoryRegistry__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "approve",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                internalType: "address",
            },
            {
                name: "votingRewardsFactory",
                type: "address",
                internalType: "address",
            },
            {
                name: "gaugeFactory",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "factoriesToPoolFactory",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "votingRewardsFactory",
                type: "address",
                internalType: "address",
            },
            {
                name: "gaugeFactory",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "isPoolFactoryApproved",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "managedRewardsFactory",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "poolFactories",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "poolFactoriesLength",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setManagedRewardsFactory",
        inputs: [
            {
                name: "_newManagedRewardsFactory",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "unapprove",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "Approve",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "votingRewardsFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "gaugeFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetManagedRewardsFactory",
        inputs: [
            {
                name: "_newRewardsFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Unapprove",
        inputs: [
            {
                name: "poolFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "votingRewardsFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "gaugeFactory",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "FallbackFactory",
        inputs: [],
    },
    {
        type: "error",
        name: "InvalidFactoriesToPoolFactory",
        inputs: [],
    },
    {
        type: "error",
        name: "PathAlreadyApproved",
        inputs: [],
    },
    {
        type: "error",
        name: "PathNotApproved",
        inputs: [],
    },
    {
        type: "error",
        name: "SameAddress",
        inputs: [],
    },
    {
        type: "error",
        name: "ZeroAddress",
        inputs: [],
    },
];
class IFactoryRegistry__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IFactoryRegistry__factory = IFactoryRegistry__factory;
IFactoryRegistry__factory.abi = _abi;
