/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeV3PoolEvents,
  IPancakeV3PoolEventsInterface,
} from "../IPancakeV3PoolEvents";

const _abi = [
  {
    type: "event",
    name: "Burn",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tickLower",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "tickUpper",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "amount",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Collect",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "tickLower",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "tickUpper",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "amount0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CollectProtocol",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Flash",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "paid0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "paid1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IncreaseObservationCardinalityNext",
    inputs: [
      {
        name: "observationCardinalityNextOld",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "observationCardinalityNextNew",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialize",
    inputs: [
      {
        name: "sqrtPriceX96",
        type: "uint160",
        indexed: false,
        internalType: "uint160",
      },
      {
        name: "tick",
        type: "int24",
        indexed: false,
        internalType: "int24",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Mint",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tickLower",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "tickUpper",
        type: "int24",
        indexed: true,
        internalType: "int24",
      },
      {
        name: "amount",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount0",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount1",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetFeeProtocol",
    inputs: [
      {
        name: "feeProtocol0Old",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "feeProtocol1Old",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "feeProtocol0New",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      {
        name: "feeProtocol1New",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Swap",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "amount1",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "sqrtPriceX96",
        type: "uint160",
        indexed: false,
        internalType: "uint160",
      },
      {
        name: "liquidity",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "tick",
        type: "int24",
        indexed: false,
        internalType: "int24",
      },
      {
        name: "protocolFeesToken0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "protocolFeesToken1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
] as const;

export class IPancakeV3PoolEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3PoolEventsInterface {
    return new Interface(_abi) as IPancakeV3PoolEventsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeV3PoolEvents {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPancakeV3PoolEvents;
  }
}
