"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPancakeV3PoolOwnerActions__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "collectProtocol",
        inputs: [
            {
                name: "recipient",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount0Requested",
                type: "uint128",
                internalType: "uint128",
            },
            {
                name: "amount1Requested",
                type: "uint128",
                internalType: "uint128",
            },
        ],
        outputs: [
            {
                name: "amount0",
                type: "uint128",
                internalType: "uint128",
            },
            {
                name: "amount1",
                type: "uint128",
                internalType: "uint128",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setFeeProtocol",
        inputs: [
            {
                name: "feeProtocol0",
                type: "uint32",
                internalType: "uint32",
            },
            {
                name: "feeProtocol1",
                type: "uint32",
                internalType: "uint32",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setLmPool",
        inputs: [
            {
                name: "lmPool",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
];
class IPancakeV3PoolOwnerActions__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IPancakeV3PoolOwnerActions__factory = IPancakeV3PoolOwnerActions__factory;
IPancakeV3PoolOwnerActions__factory.abi = _abi;
