/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeV3SwapCallback,
  IPancakeV3SwapCallbackInterface,
} from "../IPancakeV3SwapCallback";

const _abi = [
  {
    type: "function",
    name: "pancakeV3SwapCallback",
    inputs: [
      {
        name: "amount0Delta",
        type: "int256",
        internalType: "int256",
      },
      {
        name: "amount1Delta",
        type: "int256",
        internalType: "int256",
      },
      {
        name: "data",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class IPancakeV3SwapCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3SwapCallbackInterface {
    return new Interface(_abi) as IPancakeV3SwapCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeV3SwapCallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPancakeV3SwapCallback;
  }
}
