"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPancakeV3Factory__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "collectProtocol",
        inputs: [
            {
                name: "pool",
                type: "address",
                internalType: "address",
            },
            {
                name: "recipient",
                type: "address",
                internalType: "address",
            },
            {
                name: "amount0Requested",
                type: "uint128",
                internalType: "uint128",
            },
            {
                name: "amount1Requested",
                type: "uint128",
                internalType: "uint128",
            },
        ],
        outputs: [
            {
                name: "amount0",
                type: "uint128",
                internalType: "uint128",
            },
            {
                name: "amount1",
                type: "uint128",
                internalType: "uint128",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "createPool",
        inputs: [
            {
                name: "tokenA",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenB",
                type: "address",
                internalType: "address",
            },
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
        ],
        outputs: [
            {
                name: "pool",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "enableFeeAmount",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
            {
                name: "tickSpacing",
                type: "int24",
                internalType: "int24",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "feeAmountTickSpacing",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
        ],
        outputs: [
            {
                name: "",
                type: "int24",
                internalType: "int24",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "feeAmountTickSpacingExtraInfo",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
        ],
        outputs: [
            {
                name: "whitelistRequested",
                type: "bool",
                internalType: "bool",
            },
            {
                name: "enabled",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getPool",
        inputs: [
            {
                name: "tokenA",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenB",
                type: "address",
                internalType: "address",
            },
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
        ],
        outputs: [
            {
                name: "pool",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "owner",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setFeeAmountExtraInfo",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                internalType: "uint24",
            },
            {
                name: "whitelistRequested",
                type: "bool",
                internalType: "bool",
            },
            {
                name: "enabled",
                type: "bool",
                internalType: "bool",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setFeeProtocol",
        inputs: [
            {
                name: "pool",
                type: "address",
                internalType: "address",
            },
            {
                name: "feeProtocol0",
                type: "uint32",
                internalType: "uint32",
            },
            {
                name: "feeProtocol1",
                type: "uint32",
                internalType: "uint32",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setLmPool",
        inputs: [
            {
                name: "pool",
                type: "address",
                internalType: "address",
            },
            {
                name: "lmPool",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setLmPoolDeployer",
        inputs: [
            {
                name: "_lmPoolDeployer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setOwner",
        inputs: [
            {
                name: "_owner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setWhiteListAddress",
        inputs: [
            {
                name: "user",
                type: "address",
                internalType: "address",
            },
            {
                name: "verified",
                type: "bool",
                internalType: "bool",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "FeeAmountEnabled",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                indexed: true,
                internalType: "uint24",
            },
            {
                name: "tickSpacing",
                type: "int24",
                indexed: true,
                internalType: "int24",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "FeeAmountExtraInfoUpdated",
        inputs: [
            {
                name: "fee",
                type: "uint24",
                indexed: true,
                internalType: "uint24",
            },
            {
                name: "whitelistRequested",
                type: "bool",
                indexed: false,
                internalType: "bool",
            },
            {
                name: "enabled",
                type: "bool",
                indexed: false,
                internalType: "bool",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "OwnerChanged",
        inputs: [
            {
                name: "oldOwner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "newOwner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "PoolCreated",
        inputs: [
            {
                name: "token0",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "token1",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "fee",
                type: "uint24",
                indexed: true,
                internalType: "uint24",
            },
            {
                name: "tickSpacing",
                type: "int24",
                indexed: false,
                internalType: "int24",
            },
            {
                name: "pool",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SetLmPoolDeployer",
        inputs: [
            {
                name: "lmPoolDeployer",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "WhiteListAdded",
        inputs: [
            {
                name: "user",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "verified",
                type: "bool",
                indexed: false,
                internalType: "bool",
            },
        ],
        anonymous: false,
    },
];
class IPancakeV3Factory__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IPancakeV3Factory__factory = IPancakeV3Factory__factory;
IPancakeV3Factory__factory.abi = _abi;
