/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeV3PoolDerivedState,
  IPancakeV3PoolDerivedStateInterface,
} from "../IPancakeV3PoolDerivedState";

const _abi = [
  {
    type: "function",
    name: "observe",
    inputs: [
      {
        name: "secondsAgos",
        type: "uint32[]",
        internalType: "uint32[]",
      },
    ],
    outputs: [
      {
        name: "tickCumulatives",
        type: "int56[]",
        internalType: "int56[]",
      },
      {
        name: "secondsPerLiquidityCumulativeX128s",
        type: "uint160[]",
        internalType: "uint160[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "snapshotCumulativesInside",
    inputs: [
      {
        name: "tickLower",
        type: "int24",
        internalType: "int24",
      },
      {
        name: "tickUpper",
        type: "int24",
        internalType: "int24",
      },
    ],
    outputs: [
      {
        name: "tickCumulativeInside",
        type: "int56",
        internalType: "int56",
      },
      {
        name: "secondsPerLiquidityInsideX128",
        type: "uint160",
        internalType: "uint160",
      },
      {
        name: "secondsInside",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IPancakeV3PoolDerivedState__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3PoolDerivedStateInterface {
    return new Interface(_abi) as IPancakeV3PoolDerivedStateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeV3PoolDerivedState {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPancakeV3PoolDerivedState;
  }
}
