/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPancakeV3PoolImmutables,
  IPancakeV3PoolImmutablesInterface,
} from "../IPancakeV3PoolImmutables";

const _abi = [
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fee",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint24",
        internalType: "uint24",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxLiquidityPerTick",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint128",
        internalType: "uint128",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tickSpacing",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "int24",
        internalType: "int24",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token0",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token1",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IPancakeV3PoolImmutables__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV3PoolImmutablesInterface {
    return new Interface(_abi) as IPancakeV3PoolImmutablesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPancakeV3PoolImmutables {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPancakeV3PoolImmutables;
  }
}
