"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPancakeV3PoolDerivedState__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "observe",
        inputs: [
            {
                name: "secondsAgos",
                type: "uint32[]",
                internalType: "uint32[]",
            },
        ],
        outputs: [
            {
                name: "tickCumulatives",
                type: "int56[]",
                internalType: "int56[]",
            },
            {
                name: "secondsPerLiquidityCumulativeX128s",
                type: "uint160[]",
                internalType: "uint160[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "snapshotCumulativesInside",
        inputs: [
            {
                name: "tickLower",
                type: "int24",
                internalType: "int24",
            },
            {
                name: "tickUpper",
                type: "int24",
                internalType: "int24",
            },
        ],
        outputs: [
            {
                name: "tickCumulativeInside",
                type: "int56",
                internalType: "int56",
            },
            {
                name: "secondsPerLiquidityInsideX128",
                type: "uint160",
                internalType: "uint160",
            },
            {
                name: "secondsInside",
                type: "uint32",
                internalType: "uint32",
            },
        ],
        stateMutability: "view",
    },
];
class IPancakeV3PoolDerivedState__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IPancakeV3PoolDerivedState__factory = IPancakeV3PoolDerivedState__factory;
IPancakeV3PoolDerivedState__factory.abi = _abi;
