/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardsCollector,
  IRewardsCollectorInterface,
} from "../IRewardsCollector";

const _abi = [
  {
    type: "function",
    name: "collectRewards",
    inputs: [
      {
        name: "looksRareClaim",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export class IRewardsCollector__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardsCollectorInterface {
    return new Interface(_abi) as IRewardsCollectorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardsCollector {
    return new Contract(address, _abi, runner) as unknown as IRewardsCollector;
  }
}
