/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ISpotRouter, ISpotRouterInterface } from "../ISpotRouter";

const _abi = [
  {
    type: "function",
    name: "executeSwap",
    inputs: [
      {
        name: "intent",
        type: "tuple",
        internalType: "struct ISpotRouter.SwapIntent",
        components: [
          {
            name: "user",
            type: "address",
            internalType: "address",
          },
          {
            name: "tokenIn",
            type: "address",
            internalType: "address",
          },
          {
            name: "tokenOut",
            type: "address",
            internalType: "address",
          },
          {
            name: "amountIn",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "minAmountOut",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "nonce",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "adapter",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "amountOut",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class ISpotRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ISpotRouterInterface {
    return new Interface(_abi) as ISpotRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISpotRouter {
    return new Contract(address, _abi, runner) as unknown as ISpotRouter;
  }
}
