"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV3SwapCallback__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "function",
        name: "uniswapV3SwapCallback",
        inputs: [
            {
                name: "amount0Delta",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "amount1Delta",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "data",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
];
class IUniswapV3SwapCallback__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IUniswapV3SwapCallback__factory = IUniswapV3SwapCallback__factory;
IUniswapV3SwapCallback__factory.abi = _abi;
