"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageHashUtils__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "error",
        name: "ERC5267ExtensionsNotSupported",
        inputs: [],
    },
];
const _bytecode = "0x608060405234601d57600e6021565b603e602c823930815050603e90f35b6027565b60405190565b5f80fdfe60806040525f80fdfea2646970667358221220ae91a072257bb949ded1d425127864e4ba75c7eb5b912b39661d4d0a6d83d8c164736f6c634300081e0033";
const isSuperArgs = (xs) => xs.length > 1;
class MessageHashUtils__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.MessageHashUtils__factory = MessageHashUtils__factory;
MessageHashUtils__factory.bytecode = _bytecode;
MessageHashUtils__factory.abi = _abi;
