/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  MessageHashUtils,
  MessageHashUtilsInterface,
} from "../MessageHashUtils";

const _abi = [
  {
    type: "error",
    name: "ERC5267ExtensionsNotSupported",
    inputs: [],
  },
] as const;

const _bytecode =
  "0x608060405234601d57600e6021565b603e602c823930815050603e90f35b6027565b60405190565b5f80fdfe60806040525f80fdfea2646970667358221220298198d0170085b039baa29f2f5ded89a0795d6b09abfe6d60e344132b39371664736f6c63430008210033";

type MessageHashUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MessageHashUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MessageHashUtils__factory extends ContractFactory {
  constructor(...args: MessageHashUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MessageHashUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MessageHashUtils__factory {
    return super.connect(runner) as MessageHashUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessageHashUtilsInterface {
    return new Interface(_abi) as MessageHashUtilsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MessageHashUtils {
    return new Contract(address, _abi, runner) as unknown as MessageHashUtils;
  }
}
