"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SafeCast__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        type: "error",
        name: "SafeCastOverflowedIntDowncast",
        inputs: [
            {
                name: "bits",
                type: "uint8",
                internalType: "uint8",
            },
            {
                name: "value",
                type: "int256",
                internalType: "int256",
            },
        ],
    },
    {
        type: "error",
        name: "SafeCastOverflowedIntToUint",
        inputs: [
            {
                name: "value",
                type: "int256",
                internalType: "int256",
            },
        ],
    },
    {
        type: "error",
        name: "SafeCastOverflowedUintDowncast",
        inputs: [
            {
                name: "bits",
                type: "uint8",
                internalType: "uint8",
            },
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "SafeCastOverflowedUintToInt",
        inputs: [
            {
                name: "value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
];
const _bytecode = "0x608060405234601d57600e6021565b603e602c823930815050603e90f35b6027565b60405190565b5f80fdfe60806040525f80fdfea264697066735822122073548de0ba6b0561feb6526c11b043fbf9dfbceb8f759778f5bc0f69e81d224e64736f6c634300081e0033";
const isSuperArgs = (xs) => xs.length > 1;
class SafeCast__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.SafeCast__factory = SafeCast__factory;
SafeCast__factory.bytecode = _bytecode;
SafeCast__factory.abi = _abi;
