/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SpotIntegrationTest } from "./SpotIntegrationTest";
export type { SpotTest } from "./SpotTest";
