/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MinimalUniswapUniversalRouterAdapterTest__factory } from "./MinimalUniswapUniversalRouterAdapterTest__factory";
