"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MinimalUniswapUniversalRouterAdapterTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MinimalUniswapUniversalRouterAdapterTest__factory_1 = require("./MinimalUniswapUniversalRouterAdapterTest__factory");
Object.defineProperty(exports, "MinimalUniswapUniversalRouterAdapterTest__factory", { enumerable: true, get: function () { return MinimalUniswapUniversalRouterAdapterTest__factory_1.MinimalUniswapUniversalRouterAdapterTest__factory; } });
