"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VaultSpotInvariantTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VaultSpotInvariantTest__factory_1 = require("./VaultSpotInvariantTest__factory");
Object.defineProperty(exports, "VaultSpotInvariantTest__factory", { enumerable: true, get: function () { return VaultSpotInvariantTest__factory_1.VaultSpotInvariantTest__factory; } });
