"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UniswapUniversalRouterAdapterTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var UniswapUniversalRouterAdapterTest__factory_1 = require("./UniswapUniversalRouterAdapterTest__factory");
Object.defineProperty(exports, "UniswapUniversalRouterAdapterTest__factory", { enumerable: true, get: function () { return UniswapUniversalRouterAdapterTest__factory_1.UniswapUniversalRouterAdapterTest__factory; } });
