
import { saveOrder, type InsertOrder, getOrders } from '@forge/db';
import { getPairById } from './pairs';

export async function createOrder(order: Omit<InsertOrder, 'id' | 'createdAt' | 'status'>) {
    // Basic validation
    if (!order.tradingPairId || !order.userAddress || !order.side || !order.quantity || !order.price) {
        throw new Error('Missing required order fields');
    }

    const pair = await getPairById(order.tradingPairId);
    if (!pair) {
        throw new Error(`Invalid tradingPairId: ${order.tradingPairId}`);
    }

    // The 'id' and 'createdAt' fields are auto-generated by the database.
    // The 'status' field has a default value of 'open'.
    const orderToSave: InsertOrder = {
        ...order,
        // Ensure quantity and price are stored as strings to avoid precision issues
        quantity: String(order.quantity),
        price: String(order.price),
    };

    try {
        const savedOrder = await saveOrder(orderToSave);
        return savedOrder;
    } catch (error) {
        console.error("Error saving order:", error);
        // Re-throw or handle as appropriate
        throw new Error("Could not save order to the database.");
    }
}

export async function getOrdersByAccount(account: string) {
    const orders = await getOrders(account);
    return orders || [];
}
