"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CounterTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CounterTest__factory_1 = require("./CounterTest__factory");
Object.defineProperty(exports, "CounterTest__factory", { enumerable: true, get: function () { return CounterTest__factory_1.CounterTest__factory; } });
