"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FeeControllerTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FeeControllerTest__factory_1 = require("./FeeControllerTest__factory");
Object.defineProperty(exports, "FeeControllerTest__factory", { enumerable: true, get: function () { return FeeControllerTest__factory_1.FeeControllerTest__factory; } });
